-- 코드를 입력하세요
# SELECT p.PRODUCT_CODE, SUM(p.PRICE * s.SALES_AMOUNT) OVER (PARTITION BY PRODUCT_CODE) AS SALES
# FROM PRODUCT p, OFFLINE_SALE s
# WHERE p.PRODUCT_ID = s.PRODUCT_ID
# GROUP BY PRODUCT_CODE

SELECT p.PRODUCT_CODE, SUM(p.PRICE * s.SALES_AMOUNT) AS SALES
FROM PRODUCT p, OFFLINE_SALE s
WHERE p.PRODUCT_ID = s.PRODUCT_ID
GROUP BY p.PRODUCT_CODE
ORDER BY SALES DESC, p.PRODUCT_CODE ASC;