-- 코드를 입력하세요
# SELECT * FROM FIRST_HALF;
# SELECT * FROM ICECREAM_INFO;
SELECT DISTINCT a.FLAVOR
FROM FIRST_HALF a, ICECREAM_INFO i 
WHERE a.FLAVOR = i.FLAVOR AND a.TOTAL_ORDER > 3000 AND i.INGREDIENT_TYPE ='fruit_based'
ORDER BY a.TOTAL_ORDER DESC;